
-- Question 1

SELECT STAND_NAME, UPPER(STAND_NAME) AS "STAND_UPPER", LOWER(STAND_NAME) AS "STAND_LOWER", INITCAP(STAND_NAME) AS "STAND_TITLE"

FROM STAND_USER;
 
-- Question 2

SELECT USER_NAME, CATCHPHRASE, LENGTH(CATCHPHRASE) AS "PRHASE_LENGTH"

FROM STAND_USER

ORDER BY  LENGTH(CATCHPHRASE) DESC;
 
-- Question 3

SELECT STAND_NAME, SUBSTR(STAND_NAME, 1, 8) AS STAND_SHORT

FROM STAND_USER;
 
-- Question 4

SELECT STAND_NAME, INSTR(STAND_NAME, 'World') AS "WORD_POSITION"

FROM STAND_USER;
 
-- Question 5

SELECT USER_NAME, LPAD(POWER,8,'*') AS "POWER_BAR"

FROM STAND_USER;
 
-- Question 6

SELECT USER_NAME, POWER, ROUND(POWER, -2) AS "ROUNDED_POWER", TRUNC(POWER, -2) AS "TRUCATED_POWER", MOD(POWER, 300) AS "POWER_MOD_300"

FROM STAND_USER;
 
-- QUestion 7

SELECT USER_NAME, NVL2(PRECISION, TO_CHAR(PRECISION), 'Unknown') AS "PRECISION_STATUS"

FROM STAND_USER;
 
-- Question 8

SELECT USER_NAME, DEBUT_DATE, NEXT_DAY(ADD_MONTHS(DEBUT_DATE, 6), 'MONDAY') AS "TRAINING_REVIEW"

FROM STAND_USER;
 
-- Question 9

SELECT USER_NAME, ROUND(MONTHS_BETWEEN(SYSDATE, DEBUT_DATE)) AS "MONTHS_SINCE_DEBUT"

FROM STAND_USER;
 
 
-- Question 10

SELECT USER_NAME, STAND_NAME, CONCAT(CATCHPHRASE, CONCAT(' but dreams of ', "POWER" * 3)) as DREAM_STATEMENT

FROM STAND_USER;
 
-- Question 11

SELECT STAND_NAME

FROM STAND_USER

WHERE REGEXP_LIKE(STAND_NAME, 'world', 'i');
 
-- Question 12 

SELECT USER_NAME, STAND_NAME, SOUNDEX(STAND_NAME) AS "SOUND_CODE"

FROM STAND_USER;
 
-- Question 13

SELECT 
    CASE 
        WHEN MAX(CASE WHEN USER_NAME = 'DIO Brando' THEN POWER END) > MAX(CASE WHEN USER_NAME = 'Jotaro Kujo' THEN POWER END)
        THEN 'DIO reigns supreme'
        WHEN MAX(CASE WHEN USER_NAME = 'DIO Brando' THEN POWER END) < MAX(CASE WHEN USER_NAME = 'Jotaro Kujo' THEN POWER END)
        THEN 'Jotaro prevails'
        ELSE 'It''s a tie!'
    END AS RESULT
FROM STAND_USER
WHERE USER_NAME IN ('DIO Brando', 'Jotaro Kujo');
